### ISSUE TITLE
Typo in `README.md`

### ISSUE THREAD

**Issue by jembie** [akutzer/semantic-retrieval#75]
`dataset` is incorrect. It should be written as `data set`.

**Comment by akutzer** [comment]
Both data set and dataset are [valid](https://en.m.wikipedia.org/wiki/Data_set). With the later being more commonly used in ML and related topics. (Here have a look at the [pytorch docu](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html) and their usage of the word dataset...not the class)
